### ISSUE TITLE
Error when re installing GAM

### ISSUE THREAD

**Issue by genecheek** [jay0lee/GAM#1030]
Usage: gam [OPTIONS]...

GAM. Retrieve or set G Suite domain,
user, group and alias settings. Exhaustive list of commands
can be found at: https://github.com/jay0lee/GAM/wiki

Examples:
gam info domain
gam create user jsmith firstname John lastname Smith password secretpass
gam update user jsmith suspended on
gam.exe update group announcements add member jsmith
...

C:\gam>gam create project

What is your G Suite admin email address? gcheek@XXXXXXXXX.com

Go to the following link in your browser:

        https://gam-shortn.appspot.com/f23jax

Enter verification code: 4/sAEVFtvXNlYa25TeVXU3ltP2HFTCT2PG2jua_wJzjoGDSaftJ2KP5GY

ERROR: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by jay0lee** [comment]
The error indicates a problem with your network, not GAM. Please check to make sure you have a reliable network connection and no security/Antivirus software is restricting GAM's access to the network.

Marking this as closed since it's not an issue in GAM. If you need further help please reach out to the discussion group:

https://groups.google.com/forum/#!forum/google-apps-manager

**Comment by myxxmikeyxx** [comment]
I am currently getting this problem on my machine too. I tried adding a windows firewall rule and seeing if that works but still nothing.
