### ISSUE TITLE
suppress "ERROR" messages during unittests

### ISSUE THREAD

**Issue by jay0lee** [jay0lee/GAM#1068]
Running unittests:

```
python -m unittest discover -v -s ./ -p "*_test.py"
```

will currently output a lot of ERROR messages because error handling is being tested but this can be confusing in determining whether or not tests passed. See for instance:

https://travis-ci.org/jay0lee/GAM/jobs/631916180#L300-L344

ideally we'd suppress these ERROR messages during tests so test success is clearer.

**Comment by jay0lee** [comment]
@ejochman thoughts on how we might be able to implement this cleanly? I tried various patch methods for the unittests but couldn't solve for all of them.

**Comment by ejochman** [comment]
I was actually looking into this the other day. It looks like there's a flag you can use with unittest module to make it suppress all output. The problem is that, for a lot of the tests, we're asserting that the method under test produces the proper output to the right output stream. When we use that flag, it breaks all those tests, since it seems to be capturing or redirecting the output stream before the test methods can grab it. I can look into this a bit more, unless you've got any immediate leads. I'd prefer not to Frankenstein everything to make it suppress the output, but I agree it's not ideal to have it litter the build log.

**Comment by jay0lee** [comment]
Thanks Erik, agreed this is not huge priority, once you know to look for
the cumulative report at the bottom it's fine.

**Comment by ejochman** [comment]
I've looked into this a bit more and found the root of the problem. Right now, I'm patching sys.stdout and sys.stderr using @patch.object - a decorator that acts as a context manager for mocks. However, when using the "--buffer" switch with the unittest module, it [patches stdout and stderr before each test](https://github.com/python/cpython/blob/master/Lib/unittest/result.py#L65) as part of the test runner. 

Since the decorators in the test file are interpreted before the test runner even starts, the reference to the mock being passed into each test function is not the same reference that the method under test is using. The test runner effectively hijacks the mock and replaces it with its own.

One way to fix this would be to not use @patch.object decorator with stdout and stderr when we need to look at what was written to the stream. Rather, we can use a context manager inside the test function, essentially hijacking the redirection from the test runner. The downside is that, should the test fail for any reason, the test runner won't be able to output what was sent to stdout/stderr unless we have a solution that would write to both patched objects. It's technically possible, but I don't want the implementation to be too cumbersome. I think this caveat could be acceptable with the understanding that you'll have to dig a little deeper, should one of those tests fail.
