### ISSUE TITLE
create user won't immediately display backup codes

### ISSUE THREAD

**Issue by jyatsko** [jay0lee/GAM#1251]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam create user firstname lastname password changepassword off org (Org with 2FA enforced) custom_fields.something
2. gam user account show backupcodes

Expected outcome (what are you trying to do?):
After creating the account I want to output the backup codes.

Actual outcome (what errors or bad behavior do you see instead?):
Backup verification codes for account (0)

If you go in to the account in Google Admin you can see the backup codes.

**Comment by jay0lee** [comment]
"show backupcodes" will only show existing backup codes, it won't create them if they don't exist. Use:

https://github.com/jay0lee/GAM/wiki/SecurityExamples#generate-new-backup-codes-for-users

instead. Also, for questions like this that are more about how to do something rather than a proven bug, please use the discussion forum before opening an issue:

groups.google.com/g/google-apps-manager
