### ISSUE TITLE
Cannot add second domain

### ISSUE THREAD

**Issue by cksachdev** [jay0lee/GAM#139]
I tried to switch my primary domain. In the portal there is option only to create alias, so I tried the gam command ``` gam create domain xxxxxx```. This is giving the following error
```
Error 412: The customer cannot add new domains as multidomain feature for the customer is disabled. - conditionNotMet
```

Do I need to activate some settings to add secondary domain?

**Comment by GI-thub** [comment]
Hi chetan

Do you have the free version of Google Apps or are you paying a
subscription? If you go to the Admin Console and select the Billing option,
it should tell you which version you have
Secondary domains are not available on the old free version, so in order to
use the rename you would need to upgrade to the paid for version (and you
cannot roll back to the free version)

Graham



 Graham Ingleby | Cloud Computing Consultant | +44 1344 203395 |
gingleby@ancoris.com
[image: Google+] <http://google.com/+Ancoris>
<http://www.linkedin.com/company/98835>  <http://www.ancoris.com>
<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

On 2 December 2015 at 18:41, Chetan Sachdev <notifications@github.com>
wrote:

> I tried to switch my primary domain. In the portal there is option only to
> create alias, so I tried the gam command gam create domain xxxxxx. This
> is giving the following error
>
> Error 412: The customer cannot add new domains as multidomain feature for the customer is disabled. - conditionNotMet
>
> Do I need to activate some settings to add secondary domain?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/139>.
>

-- 


------------------------------

This message is for the named person's use only.  If you receive this message in error, please delete it and notify the sender.  Ancoris reserves the right to monitor all e-mail communications through its networks. Ancoris Limited, Registered in England Number: 04830784, Registered address: 5a Frascati Way, Maidenhead, Berkshire SL6 4UY. Trading Address: Lily Hill House, Lily Hill Road, Bracknell, Berkshire RG12 2SJ

------------------------------

**Comment by speedmax** [comment]
I also have the old Free edition. Tried to use Directory API (directory.customers.patch) but online tool has  problem (Invalid language error). 

I finally, got GAM going on my mac. I have seen the same problem that secondary domain is disabled. I tired to do the rename with alias but it doesn't work.

It looks like there are no way to rename primary domain that has expired.

Taylor

**Comment by GI-thub** [comment]
The old free edition doesnt support secondary domains, only aliases
The rename only supports secondary domains, not aliases
Upshot is you cannot rename an old free domain - shame as I would like to
do that myself



 Graham Ingleby | Cloud Computing Consultant | +44 1344 203395 |
gingleby@ancoris.com
[image: Google+] <http://google.com/+Ancoris>
<http://www.linkedin.com/company/98835>  <http://www.ancoris.com>
<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

On 12 December 2015 at 06:11, Taylor luk <notifications@github.com> wrote:

> I also have the old Free edition. Tried to use Directory API
> (directory.customers.patch) but online tool has problem (Invalid language
> error).
>
> I finally, got GAM going on my mac. I have seen the same problem that
> secondary domain is disabled. I tired to do the rename with alias but it
> doesn't work.
>
> It looks like there are no way to rename primary domain that has expired.
>
> Taylor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/139#issuecomment-164114218>.
>

-- 


------------------------------

This message is for the named person's use only.  If you receive this message in error, please delete it and notify the sender.  Ancoris reserves the right to monitor all e-mail communications through its networks. Ancoris Limited, Registered in England Number: 04830784, Registered address: 5a Frascati Way, Maidenhead, Berkshire SL6 4UY. Trading Address: Lily Hill House, Lily Hill Road, Bracknell, Berkshire RG12 2SJ

------------------------------

**Comment by jay0lee** [comment]
Closing issue as this is WAI.
