### ISSUE TITLE
Update gam-update.appspot.com to 3.62

### ISSUE THREAD

**Issue by jay0lee** [jay0lee/GAM#152]
We'll give 3.62 roughly a week of release time to make sure early-adopter admins don't find some critical error and then we should update the appspot.com site to point to 3.62 so that admins running older versions learn about 3.62 and hopefully upgrade.

**Comment by macsiah** [comment]
do you want reports here or the wiki?
Sent from iCloud

On Dec 23, 2015, at 08:48 AM, Jay Lee <notifications@github.com> wrote:

We'll give 3.62 roughly a week of release time to make sure early-adopter admins don't find some critical error and then we should update the appspot.com site to point to 3.62 so that admins running older versions learn about 3.62 and hopefully upgrade.

**Comment by willpolley** [comment]
The windows x64 release does not include the settings json files.

Believe this to be the cause of my hit my head against the wall for a few hours trying to figure out why the exe wouldn't successfully run from a powershell script. Replaces with .51 and .61 no problems. .62 hangs, no output.

**Comment by jay0lee** [comment]
@willpolley that's by design. The files are wrapped into the gam.exe file now. Please open a new issue about the hang with full details and steps to repro.

Jay

**Comment by jay0lee** [comment]
gam-update.appspot.com/latest-version.txt is now at 3.62. Closing.
