### ISSUE TITLE
'Me' alias?

### ISSUE THREAD

**Issue by mrapogee** [jay0lee/GAM#172]
Would make commands like `gam user j.doe delegate to me` slightly more natural.

**Comment by daethnir** [comment]
Since a gam instance is tied to a specific oauth key, and this admin account may be specific for the domain and is not a "real" user, how would it know who "me" is?

**Comment by mrapogee** [comment]
```
$ gam info user
User: xxxxxx@xxxx.com
First Name: xxxx
Last Name: xxxxx
Is a Super Admin: True
Is Delegated Admin: False
Has Agreed to Terms: True
IP Whitelisted: False
Account Suspended: False
Must Change Password: False
Google Unique ID: xxxxxxxxxxxxxxxx
Customer ID: xxxxx
Mailbox is setup: True
Included in GAL: True
Creation Time: 2016-01-05T01:00:57.000Z
Last login time: 2016-01-09T01:22:53.000Z
Google Org Unit Path: /
```

**Comment by daethnir** [comment]
Yes, 'gam info user' shows the admin's info. But I'd be shocked if the majority of places have their admin account as a real person too.

Besides, what if some place decides they want an account or group or alias called 'me'?

Implementing this feature sounds ilke a bad idea.

**Comment by nferrell** [comment]
I think it's a good idea, but would be best implemented with an alias
switch to negate issues caused by an actual user or group named me.

"gam ...... me asalias"

Considering this command would likely only get ran under an admin account
that's an actual user (I'm assuming that delegation or transfer of
ownership would be uncommon to a system account, although
anything's possible), I don't see any reason why this would be advised
against with proper precautions.

You can do a lot of damage to a domain with an assortment of different
commands in gam, I'm sure anyone using this will take care to use it
correctly. If you're using it in scripts, you can always parse the user
email into a variable then replace where you would normally put the admin
email with said variable.

On Friday, January 8, 2016, daethnir <notifications@github.com> wrote:

> Yes, 'gam info user' shows the admin's info. But I'd be shocked if the
> majority of places have their admin account as a real person too.
>
> Besides, what if some place decides they want an account or group or alias
> called 'me'?
>
> Implementing this feature sounds ilke a bad idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/172#issuecomment-170181130>.
>


-- 
Thank you for your time,
Nate Ferrell

**Comment by mrapogee** [comment]
Better than that you could use @me

You can't have a @ in a users email and an email con't have no usernam

**Comment by mrapogee** [comment]
@daethnir In my experience with a couple of companies including my current one, IT users and people in charge of adding new employees and various other tasks that require administrator rights often have them on their own accounts.

**Comment by jay0lee** [comment]
This isn't really feasible due to the ambiguity it would create. I actually have a user named me in my test domain.

One workaround would be to use an environment variable for this:

me=admin@reallylongdomainname.com
gam user jdoe@acme.com delegate to $me
