### ISSUE TITLE
Issue with vacation message

### ISSUE THREAD

**Issue by Bobbybaum** [jay0lee/GAM#184]
Hi,

I have an issue with the vacation message:

```
gam user test vacation on subject "Test" message "Test"
Setting Vacation for test@gapps.[...] (1 of 1)
```

```
gam user test show vacation
User test@gapps.[...]
 Enabled: false
 Contacts Only: false
 Domain Only: false
 Subject: None
 Message:

 Start Date: 1970-01-01
 End Date: 1969-12-31`
```

After I activated the vacation message over the Mail-GUI:

```
gam user test show vacation
User test@gapps.[...]
 Enabled: true
 Contacts Only: false
 Domain Only: false
 Subject: GAM-Test
 Message: Test123

 Start Date: 1970-01-01
 End Date: 1969-12-31
```

```
gam user test vacation on subject "Test" message "Test456"
Setting Vacation for test@gapps.[...] (1 of 1)
```

```
gam user test show vacation
User test@gapps.[...]
 Enabled: false
 Contacts Only: false
 Domain Only: false
 Subject: GAM-Test
 Message: Test123

 Start Date: 1970-01-01
 End Date: 1969-12-31
```

Regards

**Comment by glenusmaximus** [comment]
This is a bug in doVacation(). Lines 4886-4889 of gam.py set the value of `enable` to a string rather than a boolean value. Then in UpdateVacation() in gdata/apps/emailsettings/service.py, the line `properties['enable'] = gdata.apps.service._bool2str(enable)` will attempt to convert the value from boolean. Since `enable` is a string, it will always return false. Fix is to change lines 4886-4899 to:
```
  if sys.argv[4].lower() in true_values:
    enable = True
  elif sys.argv[4].lower() in false_values:
    enable = False
```

**Comment by DoctorFez** [comment]
Just wanted to chime in on this. I couldn't set vacation responder to enabled. The above solution actually worked for me. Thank you!
