### ISSUE TITLE
Switched to 2 Factor Auth

### ISSUE THREAD

**Issue by j4jones** [jay0lee/GAM#199]
I had GAM working fine for a while. Now we have switched to Google 2 Factor Auth and GAM won't work. I read I had to set an APP code - which I did. However, I have no clue where I am supposed to enter this code. - what file does it go in?? What does it replace??

**Comment by jay0lee** [comment]
GAM works fine with 2 Factor Auth because it does not directly read the user password. No app code / application specific password is needed for GAM to work. This is not really a bug / issue with GAM, if you need further help on setting GAM up with 2SV, please post to the discussion group:

https://groups.google.com/group/google-apps-manager
