### ISSUE TITLE
Error on creating filter: error 400 invalid label

### ISSUE THREAD

**Issue by cristianconti** [jay0lee/GAM#365]
On GAM 4.03 we tried to create a filter with the correct sintax explained on wiki as we done before but all we got was a error 400 invalid label: <labelname> - invalidArgument

e.
C:\GAM>gam user cconti filter from dianne@gmail.com label Dianne archive
Adding filter for cconti@comune.riccione.rn.it (1/1)

ERROR: 400: Invalid label: Dianne - invalidArgument

**Comment by taers232c** [comment]
Cristian,

The new Gmail API gam 4.03 uses does not automatically build missing labels.
Try:
gam user cconti add label Dianne
gam user cconti filter from dianne@gmail.com label Dianne archive

This has been fixed in Gam but not yet released.

In the future, post these issues here: https://groups.google.com/forum/#!forum/google-apps-manager

Ross

--
ross.scroggs@gmail.com
