### ISSUE TITLE
Error 404 while changing license tipe to an user.

### ISSUE THREAD

**Issue by Katun79** [jay0lee/GAM#447]
Hello 

I'm trying to change the assigned licenses to more than 3000 users in bulk. 
I need to switch their license from Google Vault Former Employee "vfe" to G Suite Business "gsuitebusiness".

​The command I used was: 

`gam user ​<username> update license <gsuitebusiness> from <vfe>
`
​Gam's reply is: ​

> ​​ERROR: 404: User does not have a license for specified sku and product - notFound

​But the users have the license I'm ​trying to change. 
I also tried the long SKU ID name: Google-Apps-Unlimited and Google-Vault-Former-Employee with the same error message.

How can I fix this? 
​Is a gam's issue or a Google's one? 

I'm using GAM 4.12 

Many thanks 

Tommaso

**Comment by jay0lee** [comment]
"update license" is only used for same license types (e.g. Vault and VFE).

Since these users get the Vault product from their G Suite license, they
don't have a Vault license so the VFE command needs to be an add license,
not update:

gam user <username> add license vfe

that command should give the user a VFE license which in turns removed the
G Suite Business license and any other product licenses the user has.

**Comment by Beatriz1204** [comment]
Hello jay0lee!

It's not being possible to change to Business licence from users using Google Vault Former Employee.

I have to change 8000 accounts (old painel) and i tried the following commands already:


**gam user user@domain.com update license Google-Apps-Unlimited from Google-Vault-Former-Employee

gam user user@domain.com update license Google-Apps-Unlimited from vfe

gam user user@domain.com add Google-Apps-Unlimited**

All the commands output the same error: 

**​​ERROR: 404: User does not have a license for specified sku and product - notFound**

I already checked that they have all the licences to change. 

Could you  help me?

Thanks in advance :)
