### ISSUE TITLE
GAM Backup Code Generation does not put user in grace period for SK enforcement

### ISSUE THREAD

**Issue by KSchmeeds** [jay0lee/GAM#717]
Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
Yes
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
Yes

Full steps to reproduce the issue:
1.   Have users in G-Suite Enterprise have security key only enforcement enabled
2.  Use the command "gam user <username> update backupcodes" to create a list of backup codes
3.  User attempts to sign in, but is not given the option to use the backup codes when choosing "Having trouble logging in".  (Codes generated in Admin Console will add user to grace period and enable option to sign in with a backup code)

Expected outcome (what are you trying to do?):
After the codes are generated from GAM, the user should be placed into the grace period for Security Key enforcement so they can use the backup codes.

Actual outcome (what errors or bad behavior do you see instead?):

User does not get added to grace period so they can only use the security key still.

**Comment by taers232c** [comment]
The command: `gam user <EmailAddress> update backupcodes`
generates a call to this API: https://developers.google.com/admin-sdk/directory/v1/reference/verificationCodes/generate
There is no API support for adding a user to a grace period.

These articles talk about setting up exception groups so that users can use their backup codes until they enroll in 2-Step verification

https://support.google.com/a/answer/2548882?hl=en
https://support.google.com/a/answer/2370108

Maybe when you generate the backupcodes you also add the user to an exception group.
```
gam user <EmailAddress> update backupcodes
gam update group <2StepExceptions> add member user <EmailAddress>
```

**Comment by KSchmeeds** [comment]
That's disappointing they don't have an API call for doing that, since the Grace Period has the benefit of not allowing users to add other 2FA methods, and also auto expire the codes after a set time.

**Comment by KSchmeeds** [comment]
I submitted a feature request for an API call to do this.

https://www.cloudconnectcommunity.com/ccc/ls/community/g-suite-feature-ideas/post/4910620885647360
